version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Directory for your frontend (React)
    image: asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/frontend-service:latest
    ports:
      - "80:80"
    networks:
      - my_network
    depends_on:
      - user-service
      - order-service
    environment:
      - USER_SERVICE_URL=http://user-service:8081
      - ORDER_SERVICE_URL=http://order-service:8082

  user-service:
    build:
      context: ./user-service  # Directory for your user-service (Java)
    image: asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/user-service:latest
    ports:
      - "8081:8081"
    networks:
      - my_network
    depends_on:
      - order-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # If you're using Spring profiles

  order-service:
    build:
      context: ./order-service  # Directory for your order-service (Python)
    image: asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/order-service:latest
    ports:
      - "8082:8082"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
