version: '3.8'

services:
  frontend:
    image: asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/frontend-service:latest
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - my_network
    depends_on:
      - user-service
      - order-service

  user-service:
    image: asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/user-service:latest
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    networks:
      - my_network
    depends_on:
      - order-service

  order-service:
    image: asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/order-service:latest
    build:
      context: ./order-service
    ports:
      - "8082:8082"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
